[package]
name = "sk2aac"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
